theme: jekyll-theme-minimal
logo: assets/logo.png
title: Introdução a programação com R
show_downloads: true
link_material: 'https://github.com/curso-r/main-intro-programacao/raw/master/material_do_curso.zip'
