theme: jekyll-theme-minimal
logo: assets/logo.png
title: Introdução a programação com R
show_downloads: true
link_material: 'https://github.com/curso-r/202208-intro-programacao/archive/refs/heads/main.zip'
